# Generated by Django 3.2.9 on 2021-11-23 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('task_category', models.CharField(
                    choices=[('Home Task', 'Home Task'),
                             ('Office Task', 'Office Task'),
                             ('MISC', 'Miscellaneous')],
                    max_length=20)),
                ('task_start_date', models.DateTimeField(auto_now=True)),
                ('task_end_date', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
