# Generated by Django 3.2.9 on 2021-11-18 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_alter_task_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 20, 53, 508044)),
        ),
    ]
