# Generated by Django 3.2.9 on 2021-11-19 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0006_alter_task_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 6, 54, 19, 472056)),
        ),
    ]
